/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ClassScheduleDAO;
import dao.ClassesDAO;
import dao.UserDAO;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import service.UserService;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import model.ClassScheduleModel;
import model.ClassesModel;
import service.ClassScheduleService;
import service.ClassesService;
import tableModel.ClassScheduleTableModel;

/**
 *
 * @author ramdh
 */
public class FormClassSchedule extends javax.swing.JPanel {

    private final UserService userService = new UserDAO();
    private final ClassesService classesService = new ClassesDAO();
    private final ClassScheduleService classScheduleService = new ClassScheduleDAO();
    private final ClassScheduleTableModel classScheduleTableModel = new ClassScheduleTableModel();

    public FormClassSchedule() {
        initComponents();

        SpinnerDateModel startModel = new SpinnerDateModel();
        txtStartTime.setModel(startModel);
        txtStartTime.setEditor(new JSpinner.DateEditor(txtStartTime, "HH:mm"));
        startModel.setValue(new Date());

        SpinnerDateModel endModel = new SpinnerDateModel();
        txtEndTime.setModel(endModel);
        txtEndTime.setEditor(new JSpinner.DateEditor(txtEndTime, "HH:mm"));
        endModel.setValue(new Date());

        txtClassesId.setVisible(false);
        tblClassSchedule.setModel(classScheduleTableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataClassSchedule = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassSchedule = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        addClassSchedule = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtClasses = new javax.swing.JTextField();
        btnSelectCourse = new javax.swing.JButton();
        txtClassesId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxDayOfWeek = new javax.swing.JComboBox<>();
        txtStartTime = new com.toedter.calendar.JSpinnerDateEditor();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEndTime = new com.toedter.calendar.JSpinnerDateEditor();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(899, 620));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataClassSchedule.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblClassSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClassSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassScheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClassSchedule);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Data Jadwal Kelas");

        btnTambah.setText("Tambah");
        btnTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(85, 30));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataClassScheduleLayout = new javax.swing.GroupLayout(dataClassSchedule);
        dataClassSchedule.setLayout(dataClassScheduleLayout);
        dataClassScheduleLayout.setHorizontalGroup(
            dataClassScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(dataClassScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataClassScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassScheduleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataClassScheduleLayout.setVerticalGroup(
            dataClassScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dataClassScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataClassSchedule, "card2");

        addClassSchedule.setBackground(new java.awt.Color(255, 255, 255));
        addClassSchedule.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Tambah Data Jadwal Kelas");
        addClassSchedule.add(jLabel2);
        jLabel2.setBounds(6, 6, 880, 41);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.setPreferredSize(new java.awt.Dimension(74, 30));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        addClassSchedule.add(btnSimpan);
        btnSimpan.setBounds(708, 73, 85, 30);

        btnBatalTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatalTambah.setText("Batal");
        btnBatalTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        addClassSchedule.add(btnBatalTambah);
        btnBatalTambah.setBounds(811, 73, 85, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Nama Kelas");

        txtClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClasses.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(76, 122, 227)));
        txtClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassesActionPerformed(evt);
            }
        });

        btnSelectCourse.setText("Pilih");
        btnSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCourseActionPerformed(evt);
            }
        });

        txtClassesId.setText("classesId");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Jam Mulai");

        cbxDayOfWeek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDayOfWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Hari --", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Hari");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Jam Selesai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(txtClassesId, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addComponent(cbxDayOfWeek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(cbxDayOfWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtClassesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        addClassSchedule.add(jPanel1);
        jPanel1.setBounds(0, 121, 902, 830);

        mainPanel.add(addClassSchedule, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        dataClassSchedule.setVisible(false);
        addClassSchedule.setVisible(true);

        int row = tblClassSchedule.getSelectedRow();
        jLabel2.setText("Perbarui Data Kelas");

        int classScheduleId = (int) tblClassSchedule.getModel().getValueAt(row, 0);
        ClassScheduleModel classScheduleModel = classScheduleService.getById(classScheduleId);

        txtClasses.setText(classScheduleModel.getClasses().getClassName());
        txtClassesId.setText(classScheduleModel.getClasses().getId().toString());
        cbxDayOfWeek.setSelectedItem(classScheduleModel.getDayOfWeek());
        txtStartTime.setValue(Date.from(classScheduleModel.getStartTime().atDate(LocalDate.now()).atZone(ZoneId.systemDefault()).toInstant()));
        txtEndTime.setValue(Date.from(classScheduleModel.getEndTime().atDate(LocalDate.now()).atZone(ZoneId.systemDefault()).toInstant()));
        active();
        btnSimpan.setText("Perbarui");
        btnBatalTambah.setVisible(true);
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(addClassSchedule);
        mainPanel.repaint();
        mainPanel.revalidate();

        btnSimpan.setText("Simpan");
        if (btnTambah.getText().equals("Ubah")) {
            dataTabel();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        switch (btnSimpan.getText()) {
            case "Tambah" ->
                btnSimpan.setText("Simpan");
            case "Simpan" ->
                createData();
            case "Perbarui" ->
                updateData();
            default -> {
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblClassScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassScheduleMouseClicked
        if (btnTambah.getText().equals("Tambah")) {
            btnTambah.setText("Ubah");
        }

        btnHapus.setVisible(true);
        btnBatal.setVisible(true);
    }//GEN-LAST:event_tblClassScheduleMouseClicked

    private void txtClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassesActionPerformed

    private void btnSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCourseActionPerformed
        boolean closable = true;
        DataClasses dc = new DataClasses(null, closable);
        dc.setVisible(true);

        txtClassesId.setText(dc.classesModel.getId().toString());
        txtClasses.setText(dc.classesModel.getClassName());
    }//GEN-LAST:event_btnSelectCourseActionPerformed

    private void active() {
        txtClasses.setEnabled(true);
        cbxDayOfWeek.setEnabled(true);
        txtStartTime.setEnabled(true);
        txtEndTime.setEnabled(true);
    }

    private void loadData() {
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        List<ClassScheduleModel> list = classScheduleService.getData();
        classScheduleTableModel.setData(list);

        tblClassSchedule.getColumnModel().getColumn(0).setMinWidth(0);
        tblClassSchedule.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClassSchedule.getColumnModel().getColumn(0).setWidth(0);
    }

    private void createData() {
        if (validasiInput() == true) {
            int classId = Integer.parseInt(txtClassesId.getText());
            String dayOfWeek = cbxDayOfWeek.getSelectedItem().toString();
            java.sql.Time startTime = new java.sql.Time(((Date) txtStartTime.getValue()).getTime());
            java.sql.Time endTime = new java.sql.Time(((Date) txtEndTime.getValue()).getTime());

            // Mengambil hasil relasi nya
            ClassesModel getClassesModel = classesService.getById(classId);

            ClassScheduleModel classScheduleModel = new ClassScheduleModel();
            classScheduleModel.setClasses(getClassesModel);
            classScheduleModel.setDayOfWeek(dayOfWeek);
            classScheduleModel.setStartTime(startTime.toLocalTime());
            classScheduleModel.setEndTime(endTime.toLocalTime());

            classScheduleService.addClassSchedule(classScheduleModel);
            classScheduleTableModel.addClassSchedule(classScheduleModel);

            loadData();
            resetForm();
            showPanel();
            btnSimpan.setText("Tambah");
        }
    }

    private void updateData() {
        int row = tblClassSchedule.getSelectedRow();
        if (row != -1) {
            if (validasiInput() == true) {
                int classId = Integer.parseInt(txtClassesId.getText());
                String dayOfWeek = cbxDayOfWeek.getSelectedItem().toString();
                java.sql.Time startTime = new java.sql.Time(((Date) txtStartTime.getValue()).getTime());
                java.sql.Time endTime = new java.sql.Time(((Date) txtEndTime.getValue()).getTime());

                // Mengambil hasil relasi nya
                ClassesModel getClassesModel = classesService.getById(classId);

                ClassScheduleModel classScheduleModel = new ClassScheduleModel();
                classScheduleModel.setId((int) tblClassSchedule.getModel().getValueAt(row, 0));
                classScheduleModel.setClasses(getClassesModel);
                classScheduleModel.setDayOfWeek(dayOfWeek);
                classScheduleModel.setStartTime(startTime.toLocalTime());
                classScheduleModel.setEndTime(endTime.toLocalTime());

                classScheduleService.editClassSchedule(classScheduleModel);
                classScheduleTableModel.editClassSchedule(row, classScheduleModel);
                loadData();
                resetForm();
                showPanel();
            }
        }
    }

    private void deleteData() {
        int index = tblClassSchedule.getSelectedRow();
        if (index != -1) {
            int classId = (int) tblClassSchedule.getModel().getValueAt(index, 0);
            ClassScheduleModel getClass = classScheduleService.getById(classId);

            ClassScheduleModel classScheduleModel = getClass;

            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                classScheduleService.deleteClassSchedule(classScheduleModel);
                classScheduleTableModel.deleteClassSchedule(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (txtClasses.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Kelas tidak boleh kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new FormClassSchedule());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void resetForm() {
        btnTambah.requestFocus();
        btnTambah.setText("Tambah");
        txtClasses.setText("");
        txtClassesId.setText("");
        txtStartTime.setValue(new Date());
        txtEndTime.setValue(new Date());
        cbxDayOfWeek.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addClassSchedule;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelectCourse;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbxDayOfWeek;
    private javax.swing.JPanel dataClassSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblClassSchedule;
    private javax.swing.JTextField txtClasses;
    private javax.swing.JTextField txtClassesId;
    private com.toedter.calendar.JSpinnerDateEditor txtEndTime;
    private com.toedter.calendar.JSpinnerDateEditor txtStartTime;
    // End of variables declaration//GEN-END:variables
}
