/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ClassRegistDAO;
import dao.ClassesDAO;
import dao.UserDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.ClassRegistModel;
import model.ClassesModel;
import model.UserModel;
import service.ClassRegistService;
import service.ClassesService;
import service.UserService;
import tableModel.ClassRegistTableModel;
import tableModel.UserTableModel;

/**
 *
 * @author ramdh
 */
public class FormClassRegist extends javax.swing.JPanel {

    private final ClassesService classesService = new ClassesDAO();
    private final UserService userService = new UserDAO();
    private final UserTableModel userTableModel = new UserTableModel();
    private final ClassRegistService classRegistService = new ClassRegistDAO();
    private final ClassRegistTableModel classRegistTableModel = new ClassRegistTableModel();

    public FormClassRegist() {
        initComponents();

        txtClassesId.setVisible(false);
        txtStudentId.setVisible(false);
        tblClassRegist.setModel(classRegistTableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataClassRegist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassRegist = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        addClassRegist = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtClasses = new javax.swing.JTextField();
        btnSelectClass = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        btnSelectStudent = new javax.swing.JButton();
        txtClassesId = new javax.swing.JTextField();
        txtStudentId = new javax.swing.JTextField();
        detailClassRegist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBatalDetail = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_class = new javax.swing.JLabel();
        lbl_courses = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_coach = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_total_student = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_date_range = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(899, 620));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataClassRegist.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblClassRegist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClassRegist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassRegistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClassRegist);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Data Daftar Kelas");

        btnTambah.setText("Tambah");
        btnTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(85, 30));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataClassRegistLayout = new javax.swing.GroupLayout(dataClassRegist);
        dataClassRegist.setLayout(dataClassRegistLayout);
        dataClassRegistLayout.setHorizontalGroup(
            dataClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(dataClassRegistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassRegistLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataClassRegistLayout.setVerticalGroup(
            dataClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassRegistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dataClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataClassRegist, "card2");

        addClassRegist.setBackground(new java.awt.Color(255, 255, 255));
        addClassRegist.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Tambah Data Daftar Kelas");
        addClassRegist.add(jLabel2);
        jLabel2.setBounds(6, 6, 880, 41);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.setPreferredSize(new java.awt.Dimension(74, 30));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        addClassRegist.add(btnSimpan);
        btnSimpan.setBounds(708, 73, 85, 30);

        btnBatalTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatalTambah.setText("Batal");
        btnBatalTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        addClassRegist.add(btnBatalTambah);
        btnBatalTambah.setBounds(811, 73, 85, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Nama Kelas");

        txtClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClasses.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(76, 122, 227)));
        txtClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassesActionPerformed(evt);
            }
        });

        btnSelectClass.setText("Pilih");
        btnSelectClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectClassActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Nama Siswa");

        txtStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(76, 122, 227)));
        txtStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentActionPerformed(evt);
            }
        });

        btnSelectStudent.setText("Pilih");
        btnSelectStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectStudentActionPerformed(evt);
            }
        });

        txtClassesId.setText("classId");

        txtStudentId.setText("studentId");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtClassesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSelectClass, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClassesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(614, Short.MAX_VALUE))
        );

        addClassRegist.add(jPanel1);
        jPanel1.setBounds(0, 121, 902, 830);

        mainPanel.add(addClassRegist, "card2");

        detailClassRegist.setBackground(new java.awt.Color(255, 255, 255));
        detailClassRegist.setPreferredSize(new java.awt.Dimension(1143, 620));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Detail Data Daftar Kelas");

        btnBatalDetail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatalDetail.setText("Batal");
        btnBatalDetail.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalDetailActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Informasi :");

        jLabel6.setText("Kelas :");

        jLabel8.setText("Kursus :");

        lbl_class.setText("Innovator");

        lbl_courses.setText("Pemprograman");

        jLabel11.setText("Pengajar :");

        lbl_coach.setText("Udin");

        jLabel13.setText("Total Siswa :");

        lbl_total_student.setText("50");

        jLabel15.setText("Periode Kelas :");

        lbl_date_range.setText("02 Maret 2025 s/d 31 Maret 2025");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_class))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_courses)))
                        .addGap(168, 168, 168)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_coach)
                            .addComponent(lbl_total_student))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_date_range)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(lbl_date_range))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lbl_class)
                        .addComponent(jLabel11)
                        .addComponent(lbl_coach)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_courses)
                    .addComponent(jLabel13)
                    .addComponent(lbl_total_student))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetail);

        javax.swing.GroupLayout detailClassRegistLayout = new javax.swing.GroupLayout(detailClassRegist);
        detailClassRegist.setLayout(detailClassRegistLayout);
        detailClassRegistLayout.setHorizontalGroup(
            detailClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(detailClassRegistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailClassRegistLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBatalDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailClassRegistLayout.setVerticalGroup(
            detailClassRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailClassRegistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnBatalDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );

        mainPanel.add(detailClassRegist, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        dataClassRegist.setVisible(false);
        addClassRegist.setVisible(false);
        detailClassRegist.setVisible(true);

        int row = tblClassRegist.getSelectedRow();
        jLabel4.setText("Detail Data Daftar Kelas");

        int classRegistId = (int) tblClassRegist.getModel().getValueAt(row, 0);
        ClassRegistModel classRegistModel = classRegistService.getById(classRegistId);

        loadDataDetail(classRegistId);
        lbl_class.setText(classRegistModel.getClasses().getClassName());
        lbl_courses.setText(classRegistModel.getCourses().getCourseName());
        lbl_coach.setText(classRegistModel.getCoach().getNama());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy", new Locale("id", "ID"));
        String result = classRegistModel.getClasses().getStartDate().format(formatter) + " s/d " + classRegistModel.getClasses().getEndDate().format(formatter);
        lbl_date_range.setText(result);
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(addClassRegist);
        mainPanel.repaint();
        mainPanel.revalidate();

        btnSimpan.setText("Simpan");
        if (btnTambah.getText().equals("Detail")) {
            mainPanel.add(detailClassRegist);
            mainPanel.repaint();
            mainPanel.revalidate();

            btnSimpan.setVisible(false);
            dataTabel();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void tblClassRegistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassRegistMouseClicked
        if (btnTambah.getText().equals("Tambah")) {
            btnTambah.setText("Detail");
        }

        btnHapus.setVisible(true);
        btnBatal.setVisible(true);
    }//GEN-LAST:event_tblClassRegistMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        switch (btnSimpan.getText()) {
            case "Tambah" ->
                btnSimpan.setText("Simpan");
            case "Simpan" ->
                createData();
            case "Perbarui" ->
                createData();
            default -> {
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSelectClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectClassActionPerformed
        boolean closable = true;
        DataClasses dc = new DataClasses(null, closable);
        dc.setVisible(true);

        txtClassesId.setText(dc.classesModel.getId().toString());
        txtClasses.setText(dc.classesModel.getClassName());
    }//GEN-LAST:event_btnSelectClassActionPerformed

    private void btnSelectStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectStudentActionPerformed
        boolean closable = true;
        DataStudent ds = new DataStudent(null, closable);
        ds.setVisible(true);

        txtStudentId.setText(ds.userModel.getId().toString());
        txtStudent.setText(ds.userModel.getNama());
    }//GEN-LAST:event_btnSelectStudentActionPerformed

    private void txtStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentActionPerformed

    private void txtClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassesActionPerformed

    private void btnBatalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalDetailActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalDetailActionPerformed

    private void active() {
        txtClasses.setEnabled(true);
        txtStudent.setEnabled(true);
    }

    private void loadData() {
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        List<ClassRegistModel> list = classRegistService.getData();
        classRegistTableModel.setData(list);

        tblClassRegist.getColumnModel().getColumn(0).setMinWidth(0);
        tblClassRegist.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClassRegist.getColumnModel().getColumn(0).setWidth(0);
    }

    private void loadDataDetail(int id) {
        System.out.println("Masuk sini ndak? : " + id);
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        tblDetail.setModel(userTableModel);

        List<UserModel> list = classRegistService.getDataStudentById(id);
        userTableModel.setData(list);

        lbl_total_student.setText(Integer.toString(userTableModel.getRowCount()));
        tblDetail.getColumnModel().getColumn(0).setMinWidth(0);
        tblDetail.getColumnModel().getColumn(0).setMaxWidth(0);
        tblDetail.getColumnModel().getColumn(0).setWidth(0);
    }

    private void createData() {
        if (validasiInput() == true) {
            int classId = Integer.parseInt(txtClassesId.getText());
            int studentId = Integer.parseInt(txtStudentId.getText());

            // Mengambil hasil relasi nya
            ClassesModel getClassesModel = classesService.getById(classId);
            UserModel getStudentModel = userService.getById(studentId);

            ClassRegistModel classRegistModel = new ClassRegistModel();
            classRegistModel.setClasses(getClassesModel);
            classRegistModel.setStudent(getStudentModel);

            classRegistService.addClassRegist(classRegistModel);
            classRegistTableModel.addClassRegist(classRegistModel);

            loadData();
            resetForm();
            showPanel();
            btnSimpan.setText("Tambah");
        }
    }

    private void deleteData() {
        int index = tblClassRegist.getSelectedRow();
        if (index != -1) {
            int classId = (int) tblClassRegist.getModel().getValueAt(index, 0);
            ClassRegistModel getClass = classRegistService.getById(classId);

            ClassRegistModel classRegistModel = getClass;

            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                classRegistService.deleteClassRegist(classRegistModel);
                classRegistTableModel.deleteClassRegist(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (txtClasses.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Kelas tidak boleh kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new FormClassRegist());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void resetForm() {
        btnTambah.requestFocus();
        btnTambah.setText("Tambah");
        txtClasses.setText("");
        txtClassesId.setText("");
        txtStudent.setText("");
        txtStudentId.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addClassRegist;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalDetail;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelectClass;
    private javax.swing.JButton btnSelectStudent;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel dataClassRegist;
    private javax.swing.JPanel detailClassRegist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_class;
    private javax.swing.JLabel lbl_coach;
    private javax.swing.JLabel lbl_courses;
    private javax.swing.JLabel lbl_date_range;
    private javax.swing.JLabel lbl_total_student;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblClassRegist;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTextField txtClasses;
    private javax.swing.JTextField txtClassesId;
    private javax.swing.JTextField txtStudent;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
